 

services:
  

  backend:
    build:
      context: .
      dockerfile: dev.Dockerfile

  
    volumes:
      - ./container:/container
      - ../.vscode-server/container:/root/.vscode-server
    secrets:
      - openai.txt

  pgvector:
    image: pgvector/pgvector:0.7.3-pg16
    environment:
      POSTGRES_USER: langchain
      POSTGRES_PASSWORD: langchain
      POSTGRES_DB: langchain
    volumes:
      - vectordb-pg:/var/lib/postgresql/data



volumes:
  vectordb-pg:

secrets:
  openai.txt:
    file: ./secrets/openai.txt
